language: python
dist: xenial
jobs:
  include:
  - python: "2.6"
    dist: trusty
  - python: "2.7"
  - python: "3.2"
    dist: trusty
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2; fi
- pip install pydiatra
- pip install $pyflakes
script:
- python test.py --verbose
- python -m pydiatra .
- pyflakes .
- python setup.py install
- cd /
- python -c 'import forknanny'

# vim:ts=2 sts=2 sw=2 et
