language: python
dist: trusty
jobs:
  include:
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
  - python: "3.8-dev"
    dist: xenial
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install pydiatra
- python3 -m pip install $pyflakes
script:
- python3 test.py --verbose
- python3 -m pydiatra .
- python3 -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
