name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '2.7'
          os: ubuntu-22.04
        - python: '3.8'
          os: ubuntu-22.04
        - python: '3.9'
          os: ubuntu-22.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
        - python: '3.13'
          os: ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      if: matrix.python != '2.7'
      with:
        python-version: ${{matrix.python}}
    - name: set up Python 2.7 (with APT + get-pip)
      if: matrix.python == '2.7'
      run: |
        sudo apt-get install python2
        sudo ln -sf python2 /usr/bin/python
        wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
        sudo python get-pip.py
        rm get-pip.py
    - name: install setuptools (if distutils is missing)
      if: env.pythonLocation
      run: |
        if ! [ -d ${{env.pythonLocation}}/lib/python*/distutils/ ]; then
          python -m pip install setuptools
        fi
    - name: run tests
      run: |
        python test.py --verbose
    - name: install via setup.py
      run: |
        python setup.py install --user
    - name: check import
      run: |
        cd /
        python -c 'import forknanny'
    - name: clean
      run: |
        python setup.py clean -a
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
